spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: sang7952@
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting
    producer:
      bootstrap-servers: localhost:9092
  jpa:
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher