spring:
  datasource:
    url: jdbc:mysql://capstone-db-server.cfajzfxucmki.ap-northeast-2.rds.amazonaws.com:3306/agora
    username: admin
    password: sang7952
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting
    producer:
      bootstrap-servers: localhost:9092
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    version: openapi_3_0
  packages-to-scan: capstone.agora.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html