spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: sang7952@
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting
    producer:
      bootstrap-servers: localhost:9092